version: '3'

services:

    pgdb:
        image: postgres
        env_file: /var/fastfood/.env
        container_name: pgdb

    adminer:
        image: adminer
        restart: always
        ports:
           - 8080:8080
